# -*- coding: utf-8 -*-
"""Assemble a release-ready code archive for the JAML / M2-M9 project, initialise a local
git repository around it, and make the code-availability wording in the manuscript precise.

Why not push and mint a DOI here?  A DOI requires an authenticated GitHub/Zenodo account and
this machine has neither a token nor the `gh` CLI.  Inventing a DOI (or a repository URL) is
not an option, so this script produces everything that can be produced offline and prints the
exact commands that remain.

Outputs
  JAML_M2M9_code_release/            the release tree (code, derived tables, supplementary, metadata)
  JAML_M2M9_code_release.tar.gz      the archive a repository/Zenodo upload consumes
  JAML_M2M9_code_release/SHA256SUMS.txt
  (git init + one commit inside the tree)

Then: python scripts/67_finalise_review2.py --doi 10.5281/zenodo.XXXXXXX --url https://...
"""
import datetime
import hashlib
import io
import os
import shutil
import subprocess
import sys
import tarfile

sys.stdout.reconfigure(encoding="utf-8")

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCRIPTS = os.path.join(BASE, "scripts")
RESULTS = os.path.join(BASE, "results")
PKG = os.path.join(BASE, "M2-M9深化研究稿")
SUP = os.path.join(PKG, "04_Supplementary")
JTM = os.path.join(BASE, "JTM投稿_M2M9")
REL = os.path.join(BASE, "JAML_M2M9_code_release")

TITLE = ("Compartmentally separated JAML and CXADR in lung adenocarcinoma: myeloid-dominant "
         "expression, and ID2 as the only noise-calibrated candidate regulator")
VERSION = "1.0.0"
DATE = datetime.date.today().isoformat()

KEY_RESULTS = [
    "m2_tcga_jaml_partial_corr.csv", "m2_marker_specificity.csv", "m2_marker_profile_similarity.csv",
    "m2_tcga_stage_jaml.csv", "cross_dataset_compartment_pct.csv",
    "reviewer_R1_ID2_relative_effect.csv", "reviewer_R2_TCGA_parameterisation.csv",
    "reviewer_R3_M5_power.json", "refcheck_m2m9.json", "refcheck_m2m9.md",
]

DATA_SOURCES = """# Data sources

All input data are public. Nothing in this release redistributes raw data.

| Dataset | Accession / URL | Used for |
|---|---|---|
| GSE131907 | GEO | discovery single-cell cohort (LUAD, 208,506 cells) |
| GSE127465 | GEO | independent replication (treatment-naive NSCLC, 54,773 cells) |
| GSE135222 | GEO | checkpoint-blockade cohort (n = 27, PFS) |
| GSE126044 | GEO | evaluated and rejected: the gene of interest is absent from its matrix |
| TCGA-LUAD | https://portal.gdc.cancer.gov/ (expression via UCSC Xena) | tissue-level deconvolution and survival |
| DepMap 22Q2 | https://depmap.org/ | CRISPR (Chronos) gene effect |
| OneK1K single-cell eQTL | eQTL Catalogue, study QTS000038 | genetic anchor (not re-estimated here) |
| LUAD GWAS (McKay et al.) | GWAS Catalog, GCST004744 | genetic anchor (not re-estimated here) |

Reference resources pulled at run time: CollecTRI (via decoupleR), the liana consensus
ligand-receptor resource, the CellOracle human promoter base GRN (hg38), EPIC / MCP-counter /
CIBERSORT-LM22 signatures, ABSOLUTE tumour purity (TCGA clinical matrix).
"""

README = """# Code for: {title}

Release {version} ({date}) — every number, figure and table in the manuscript is generated by the
scripts in `code/`. Derived tables are in `results/`; the numbered supplementary files are in
`supplementary/`.

## What this repository contains

The study asks where *JAML* acts in lung adenocarcinoma and who regulates it, using public data
only. It does not report a new Mendelian randomisation estimate. The eight analyses and their
controls are listed in Table 1 of the manuscript; the text of the manuscript states explicitly
which claims the data do not support.

## Layout

```
code/            analysis scripts, in the order they were run
code/d_workspace/ the M4 (CellOracle) and M8 (decoupleR) pipeline, which was run in a second
                  workspace; 18 file names exist in both trees and these copies are the ones
                  that produced the submitted results
results/         derived result tables underlying the figures and tables
supplementary/   the 17 supplementary files as submitted (Supplementary Material 1-17)
README.md        this file
DATA_SOURCES.md  accessions and versions of every public input
LICENSE          MIT (code); see the note below
CITATION.cff     citation metadata (GitHub and Zenodo read this)
SHA256SUMS.txt   checksums for every file in this release
```

## Reproducing

Python 3.13 with `pandas`, `numpy`, `scipy`, `scanpy`, `anndata`, `decoupler`, `celloracle`,
`liana`; R 4.6 with `survival`, `data.table`, `ggplot2`. `celloracle` additionally requires
`velocyto`, which has no Windows wheel on PyPI — it was built locally from source with Cython
3.3.0 and Rtools44 GCC 13.3.0 (`code/40_verify_velocyto_minimal.py` verifies it against a NumPy
reference implementation, max |delta| = 8.9e-16).

Scripts read data from a project-local `rawdata/` tree and write to `results/`; paths appear as
module constants at the top of each file. The M4 cell-oracle figures are re-plotted (rather than
re-fitted) by `code/m8_fig6_replot.py`, which reproduces the pipeline's own saved values — it
asserts the recomputed permutation distribution equals the recorded one before writing a figure.

## Two things a reader should know about our controls

1. `calculate_randomized_coef_table()` in CellOracle caches its randomised coefficient matrix
   (default seed 123, computed once). Repeating a call without changing the seed re-uses the same
   randomised network. Our paired control therefore re-seeds on every replicate.
2. The global noise ceiling is the largest randomised reading observed across non-degenerate
   factors — an empirical maximum over a finite number of draws. It sits below the true null
   maximum, so the screen is liberal, not conservative; and with five replicates per factor no
   empirical P value below 1/6 is attainable. What carries weight is the size of the excess.

## Licence

`LICENSE` contains the MIT licence for the code. The derived tables and supplementary files are
research data; if you would prefer them under CC BY 4.0, or prefer a different code licence,
change `LICENSE` before publishing the archive — the choice is the authors'.

## Citation

See `CITATION.cff`. A DOI is minted from this archive (Zenodo) and quoted in the manuscript's
data-availability statement.
"""

MIT = """MIT License

Copyright (c) {year} Huayong Liu and co-authors

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""

CITATION = """cff-version: 1.2.0
message: "If you use this code, please cite the manuscript and this archive."
title: "{title}"
version: {version}
date-released: {date}
license: MIT
type: software
authors:
  - family-names: Liu
    given-names: Huayong
    orcid: "https://orcid.org/0009-0007-8106-0425"
    affiliation: "Department of Pulmonary and Critical Care Medicine, Shenzhen Nanshan District People's Hospital (Shenzhen University Affiliated Nanshan Hospital)"
  - family-names: Gong
    given-names: Xuefang
  - family-names: Xiong
    given-names: Bo
  - family-names: Wang
    given-names: Jiadun
  - family-names: Tao
    given-names: Chunyan
  - family-names: Peng
    given-names: Zhuoming
  - family-names: Chen
    given-names: Jiming
keywords:
  - JAML
  - AMICA1
  - CXADR
  - lung adenocarcinoma
  - single-cell RNA sequencing
  - deconvolution
  - transcription factor perturbation
  - CellOracle
repository-code: "TO BE COMPLETED WHEN THE REPOSITORY URL IS KNOWN"
"""

ZENODO = """{{
  "title": "{title}",
  "upload_type": "software",
  "version": "{version}",
  "publication_date": "{date}",
  "license": "MIT",
  "access_right": "open",
  "creators": [
    {{"name": "Liu, Huayong", "orcid": "0009-0007-8106-0425",
      "affiliation": "Department of Pulmonary and Critical Care Medicine, Shenzhen Nanshan District People's Hospital (Shenzhen University Affiliated Nanshan Hospital)"}},
    {{"name": "Gong, Xuefang", "affiliation": "Department of Pulmonary and Critical Care Medicine, Shenzhen Nanshan District People's Hospital (Shenzhen University Affiliated Nanshan Hospital)"}},
    {{"name": "Xiong, Bo", "affiliation": "Department of Pulmonary and Critical Care Medicine, Shenzhen Nanshan District People's Hospital (Shenzhen University Affiliated Nanshan Hospital)"}},
    {{"name": "Wang, Jiadun", "affiliation": "Department of Pulmonary and Critical Care Medicine, Shenzhen Nanshan District People's Hospital (Shenzhen University Affiliated Nanshan Hospital)"}},
    {{"name": "Tao, Chunyan", "affiliation": "Department of Pulmonary and Critical Care Medicine, Shenzhen Nanshan District People's Hospital (Shenzhen University Affiliated Nanshan Hospital)"}},
    {{"name": "Peng, Zhuoming", "affiliation": "Department of Pulmonary and Critical Care Medicine, Shenzhen Nanshan District People's Hospital (Shenzhen University Affiliated Nanshan Hospital)"}},
    {{"name": "Chen, Jiming", "affiliation": "Department of Pulmonary and Critical Care Medicine, Shenzhen Nanshan District People's Hospital (Shenzhen University Affiliated Nanshan Hospital)"}}
  ],
  "description": "Analysis code and derived result tables for a target-triage study of JAML in lung adenocarcinoma. Every number, figure and table in the manuscript is generated by these scripts. Derived tables and the 17 supplementary files are included; raw public data are not redistributed.",
  "keywords": ["JAML", "AMICA1", "CXADR", "lung adenocarcinoma", "single-cell RNA sequencing", "deconvolution", "transcription factor perturbation", "CellOracle"]
}}
"""


def log(*a):
    print(*a, flush=True)


def sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def build_tree():
    """Build in place.

    The sandbox intercepts bulk deletes (and refuses to rename a directory that another
    handle has open), so nothing is ever removed: new content overwrites, and any file that
    this run no longer produces is moved into `_superseded/`.
    """
    rel = os.path.abspath(REL)
    if os.path.isdir(rel):
        log("  building in place (nothing is deleted)")
    for sub in ("code", "code/d_workspace", "results", "supplementary"):
        os.makedirs(os.path.join(rel, *sub.split("/")), exist_ok=True)

    expected = set()

    n_code = 0
    for f in sorted(os.listdir(SCRIPTS)):
        if f.endswith(".py") and ".bak" not in f:
            shutil.copy2(os.path.join(SCRIPTS, f), os.path.join(rel, "code", f))
            expected.add("code/" + f)
            n_code += 1
    # M4/M8 pipeline lives in the D-drive workspace; 18 names exist in both trees and the
    # D-drive copies are authoritative, so they are kept in their own folder.
    n_d = 0
    d_dir = r"D:\workbuddy工作空间\JAML深度研究\scripts"
    if os.path.isdir(d_dir):
        for f in sorted(os.listdir(d_dir)):
            if f.endswith(".py"):
                shutil.copy2(os.path.join(d_dir, f), os.path.join(rel, "code", "d_workspace", f))
                expected.add("code/d_workspace/" + f)
                n_d += 1

    n_res = 0
    for f in KEY_RESULTS:
        src = os.path.join(RESULTS, f)
        if os.path.exists(src):
            shutil.copy2(src, os.path.join(rel, "results", f))
            expected.add("results/" + f)
            n_res += 1

    n_sup = 0
    for f in sorted(os.listdir(SUP)):
        p = os.path.join(SUP, f)
        if os.path.isfile(p) and not f.endswith(".bak_review2"):
            shutil.copy2(p, os.path.join(rel, "supplementary", f))
            expected.add("supplementary/" + f)
            n_sup += 1

    docs = {"README.md": README.format(title=TITLE, version=VERSION, date=DATE),
            "DATA_SOURCES.md": DATA_SOURCES,
            "LICENSE": MIT.format(year=DATE[:4]),
            "CITATION.cff": CITATION.format(title=TITLE, version=VERSION, date=DATE),
            ".zenodo.json": ZENODO.format(title=TITLE, version=VERSION, date=DATE),
            ".gitignore": "__pycache__/\n*.pyc\n_superseded/\n*.bak_*\n"}
    for name, body in docs.items():
        io.open(os.path.join(rel, name), "w", encoding="utf-8").write(body)
        expected.add(name)

    # anything left over goes to _superseded/ rather than being deleted
    moved = 0
    for root, dirs, files in os.walk(rel):
        dirs[:] = [d for d in dirs if d not in (".git", "_superseded")]
        for f in files:
            if f == "SHA256SUMS.txt":
                continue
            rp = os.path.relpath(os.path.join(root, f), rel).replace("\\", "/")
            if rp not in expected:
                dst = os.path.join(rel, "_superseded", rp.replace("/", os.sep))
                os.makedirs(os.path.dirname(dst), exist_ok=True)
                os.replace(os.path.join(root, f), dst)
                moved += 1
    if moved:
        log("  %d superseded file(s) moved to _superseded/" % moved)

    # checksums over everything except the sums file and the superseded pile
    lines, n_files = [], 0
    for root, dirs, files in os.walk(rel):
        dirs[:] = [d for d in dirs if d not in (".git", "_superseded")]
        for f in sorted(files):
            if f == "SHA256SUMS.txt":
                continue
            p = os.path.join(root, f)
            relp = os.path.relpath(p, rel).replace("\\", "/")
            lines.append("%s  %s" % (sha256(p), relp))
            n_files += 1
    io.open(os.path.join(rel, "SHA256SUMS.txt"), "w", encoding="utf-8").write("\n".join(lines) + "\n")
    log("  code %d (+%d in code/d_workspace), derived results %d, supplementary %d, checksummed files %d"
        % (n_code, n_d, n_res, n_sup, n_files))
    return n_files


def make_tarball():
    tar = REL + ".tar.gz"
    skip = (os.sep + "_superseded", os.sep + ".git" + os.sep)
    with tarfile.open(tar, "w:gz") as t:
        base = os.path.dirname(REL)
        for root, dirs, files in os.walk(REL):
            dirs[:] = [d for d in dirs if d not in ("_superseded", ".git")]
            for f in sorted(files):
                p = os.path.join(root, f)
                if any(s in p for s in skip):
                    continue
                t.add(p, arcname=os.path.join(os.path.basename(REL), os.path.relpath(p, REL)))
    digest = sha256(tar)
    io.open(tar + ".sha256", "w", encoding="utf-8").write(
        "%s  %s\n" % (digest, os.path.basename(tar)))
    log("  wrote %s (%.1f MB)" % (os.path.basename(tar), os.path.getsize(tar) / 1e6))
    log("  sha256 %s" % digest)
    log("  checksum also written to %s.sha256 (Zenodo direct upload verifies this)" % os.path.basename(tar))
    return tar


def git_init():
    try:
        subprocess.run(["git", "--version"], check=True, capture_output=True)
    except Exception as e:
        log("  git unavailable (%s) - skipping repository init" % e)
        return
    cmds = [
        ["git", "init", "-q"],
        # _superseded/ is the on-disk recycling bin for files this build no longer produces; it
        # must never be published, so untrack it before staging (no-op if it was never tracked).
        ["git", "rm", "-r", "--cached", "-q", "--ignore-unmatch", "_superseded"],
        ["git", "add", "-A"],
        ["git", "-c", "user.name=Huayong Liu", "-c", "user.email=xingxinghuoshu@163.com",
         "commit", "-q", "-m",
         "Release %s: analysis code and derived result tables\n\n%s" % (VERSION, TITLE)],
    ]
    for c in cmds:
        r = subprocess.run(c, cwd=REL, capture_output=True, text=True)
        if r.returncode != 0:
            log("  git %s -> %s" % (c[1], (r.stderr or r.stdout).strip()[:160]))
            return
    tracked = subprocess.run(["git", "ls-files"], cwd=REL, capture_output=True, text=True).stdout
    n_bad = len([l for l in tracked.splitlines() if l.startswith("_superseded/")])
    if n_bad:
        log("  WARNING: %d superseded path(s) still tracked - they would be pushed" % n_bad)
    r = subprocess.run(["git", "log", "--oneline", "-1"], cwd=REL, capture_output=True, text=True)
    log("  git repository: %d tracked files, head %s" % (len(tracked.splitlines()), r.stdout.strip()))


AVAIL_OLD_EN = ("All analysis scripts, the derived result tables underlying every figure and table, "
                "and the machine-readable reference-verification record are provided as Additional file 11; "
                "that archive will be deposited in a public repository with a DOI before publication and "
                "remains available from the corresponding author on reasonable request in the interim.")
AVAIL_NEW_EN = ("All analysis scripts, the derived result tables underlying every figure and table, and the "
                "machine-readable reference-verification record are provided as Supplementary Material 17. "
                "An identical archive (version 1.0.0) is being deposited in a public repository; its DOI will "
                "be quoted here once issued, and the archive remains available from the corresponding author "
                "on reasonable request in the interim.")


def main():
    log("[1] release tree")
    n = build_tree()
    log("[2] tarball")
    make_tarball()
    log("[3] local git repository")
    git_init()
    log("[4] remaining steps (cannot be done without your account):")
    print("""
  # 1. create an empty PUBLIC repository, then:
  cd "%s"
  git remote add origin https://github.com/<your-account>/<repo>.git
  git branch -M main
  git push -u origin main

  # 2a. DOI via GitHub release (recommended, gives a versioned DOI):
  #     - sign in to https://zenodo.org with GitHub, open Settings -> GitHub,
  #       toggle ON the repository you just pushed;
  #     - back on GitHub, create a Release (tag v%s);
  #     - Zenodo then mints a DOI automatically and shows the badge.

  # 2b. or DOI by direct upload: https://zenodo.org/uploads/new
  #     upload  %s
  #     (metadata is pre-filled from .zenodo.json inside the archive)

  # 3. write the DOI back into both manuscripts and rebuild the docx:
  python scripts/67_finalise_review2.py --doi 10.5281/zenodo.XXXXXXX --url https://github.com/<you>/<repo>
""" % (REL, VERSION, os.path.basename(REL) + ".tar.gz"))


if __name__ == "__main__":
    main()
